---
- hosts: all
  tasks: 
  - name: installing webserver
    apt: 
      name: apache2
      state: present
  - name: Installing tree
    apt:
      name: tree
      state: present
  - service:
    name: apache2
    state: restarted