---
- hosts: all
  tasks: 
  - name: installing webserver
    apt: 
      name: apache2
      state: present
  - name: Installing tree
    apt:
      name: tree
      state: present
  - name: I want to restart the apache2 servives
    service:
      name: apache2
      state: restarted