---
- hosts: mywebservers
  tasks: 
  - name: installing webserver
    apt: 
      name: {{"mywebpackonubuntu"}}
      state: present
    when: ansible_os_family =="Debian"

  - name: I want to install apache2 on Redhat manchine
    yum:
      name: {{"mywebpackonredhat"}}
      state: present
    when: ansible_os_family =="Redhat"
  
  - name: installing webserver
    apt: 
      name: {{"myjavaonubuntu"}}
      state: present
    when: ansible_os_family =="Debian"

  - name: I want to install apache2 on Redhat manchine
    yum:
      name: {{"myjavaonredhat"}}
      state: present
    when: ansible_os_family =="Redhat"